# Generated by Django 3.0.6 on 2020-06-13 02:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('McViewer', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='privatenetwork',
            old_name='user',
            new_name='users',
        ),
    ]
